### ISSUE TITLE
Minimum Cuda Memory Required for SAM2CLIP Training

### ISSUE THREAD

**Issue by WuHenry-0609** [HarborYuan/ovsam#18]
Thank you for all your hard work!
I encountered a "**Cuda out of memory**" error when running "**bash tools/dist.sh train seg/configs/sam2clip/sam2clip_vith_rn50x16.py 8**" on **8 RTX2080Ti GPUs** to train SAM2CLIP. So, what is the minimum cuda memory required for SAM2CLIP training?
I‘m looking forward to your reply.

**Comment by HarborYuan** [comment]
Hi @WuHenry-0609 ,

If you are using 2080Ti, which is with 12GB RAM I guess, you may encounter CUDA OOM due to the GPU RAM limitation. Please consider changing the batchsize on each GPU from `2` to `1` ([here](https://github.com/HarborYuan/ovsam/blob/126ba2b6422f5bec8bb9fad271c4cda16efde5ee/seg/configs/_base_/datasets/sam_img.py#L40)).

You can also try GPUs with RAM more than 24GB.
