### ISSUE TITLE
novel_score is very low (checkpoint evalutation on test)

### ISSUE THREAD

**Issue by miquel-espinosa** [HarborYuan/ovsam#37]
Hi. Thanks for the code and paper.

When I evaluate the provided checkpoint with the codebase, I am able to reproduce all the COCO values that were reported in the paper.

But I have a question about the values printed in the terminal.  Is the `novel_score` the accuracy on class prediction for the novel classes? Why is `novel_score` so low compared to `base_score`?

```
mmengine - INFO - Epoch(test) [1209/1209]    miou: 0.6791  base_iou: 0.6835  novel_iou: 0.6521 
                                             score: 76.7359  base_score: 87.4120  novel_score: 11.1742 
                                             data_time: 0.0165  time: 0.2565
```

Thanks.

**Comment by HarborYuan** [comment]
Hi @miquel-espinosa ,

Thanks for your interest in our work.

> But I have a question about the values printed in the terminal. Is the novel_score the accuracy on class prediction for the novel classes? Why is novel_score so low compared to base_score?

The `score` corresponds to the accuracy of our paper. For the `novel_score`, it is just a value that can be used as a reference because this does not conform to the test process of novel category classification. In our method, the classifier includes all categories, which means that objects of the new category may be classified as the base category. This situation may happen, especially when the new category and the old category are visually similar.

**Comment by 1523900304** [comment]
Hello, I reasoned that coco2017 got the same result as him.    "miou": 0.6791341304779053,
    "base_iou": 0.6835447549819946,
    "novel_iou": 0.6520487666130066,
    "score": 76.74510955810547,
    "base_score": 87.42625427246094,
    "novel_score": 11.152335166931152,
    "data_time": 0.025427920646762137,
    "time": 0.538555013038976
Why is Miou only 0.68?

**Comment by HarborYuan** [comment]
Hi @1523900304, please note that the maximum iou is 1.
