### ISSUE TITLE
_pickle.UnpicklingError: invalid load key, 'v'.

### ISSUE THREAD

**Issue by CVHub520** [HarborYuan/ovsam#4]
Hello,

When I attempt to execute the test case using the following command:

```bash
python tools/test.py seg/configs/ovsam/ovsam_coco_rn50x16_point.py
```

I encountered the following error. Could you please guide me on how to resolve it? Any assistance would be greatly appreciated.

Error Details:
```bash
Traceback (most recent call last):
  File "tools/test.py", line 177, in <module>
    main()
  File "tools/test.py", line 141, in main
    runner = Runner.from_cfg(cfg)
  ...
  ...
  ...
  _pickle.UnpicklingError: invalid load key, 'v'.
```

Thank you!

**Comment by CVHub520** [comment]
It seems like I've identified the issue; it appears that the model wasn't downloaded completely.

**Comment by HarborYuan** [comment]
The inference command should look like this:
```commandline
bash tools/dist.sh test seg/configs/ovsam/ovsam_coco_rn50x16_point.py 8
```
where 8 is your number of GPUs.

Your issue is because python considers `./tools` as the project path and cannot find the config path. If you insist on your command, which only supports single-gpu inference, you can add `PYTHONPATH=.` before your command.

**Comment by HarborYuan** [comment]
> It seems like I've identified the issue; it appears that the model wasn't downloaded completely.

That sounds reasonable. Please let me know if you have any other questions.
